### ISSUE TITLE
Transaction timeout for shortest path queries

### ISSUE THREAD

**Issue by egglessness** [SpecterOps/BloodHound#46]
Hi! Thank you for sharing this awesome tool.

I am currently unable to run any of the "Shortest Path" queries. Every time I try, I receive an error and, by looking at the app logs, I see the following message:

```
{
  "level": "warn",
  "time": "2023-08-17T16:02:08.765086Z",
  "message": "Writing API Error. Status: 500. Message: [{ driver error: Neo4jError: Neo.ClientError.Transaction.TransactionTimedOut (The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. The transaction has not completed within the specified timeout (dbms.transaction.timeout). You may want to retry with a longer timeout. ) - query: match p = shortestPath((n)-[:Owns|GenericAll|GenericWrite|WriteOwner|WriteDacl|MemberOf|ForceChangePassword|AllExtendedRights|AddMember|HasSession|Contains|GPLink|AllowedToDelegate|TrustedBy|AllowedToAct|AdminTo|CanPSRemote|CanRDP|ExecuteDCOM|HasSIDHistory|AddSelf|DCSync|ReadLAPSPassword|ReadGMSAPassword|DumpSMSAPassword|SQLAdmin|AddAllowedToAct|WriteSPN|AddKeyCredentialLink|SyncLAPSPassword|WriteAccountRestrictions*1..]->(g:Group)) where g.objectid ends with \"-512\" and n <> g return p}]"
}
```

It seems that the transaction times out before completing. 

Looking at the Neo4j configuration, the transaction timeout is set to 0 (default), meaning that it should run indefinitely.

```
call dbms.listConfig("dbms.transaction.timeout")

[
    ..., 
    "_fields": [
      "dbms.transaction.timeout",
      "The maximum time interval of a transaction within which it should be completed.",
      "0s",
      true
    ],
   ...
]
```

Could the problem be located in the Neo4j driver? Maybe setting an explicit longer timeout may help

**Comment by StephenHinck** [comment]
Hey there, you have a couple of options here that you could look at:

- There's a bug on this particular functionality that will get fixed in our next release, but afterward, if using the API, you can include `Prefer: wait=60` as a header in your request, and this will extend the timeout.
- In the environment variables of your bloodhound container, include `bhe_disable_cypher_qc=true`. This should turn off the timeout and memory constraint limitations on your cypher queries (however, doing so may risk excessive consumption of resources that could result in hangs or crashes of Neo4J).

I'll close this issue for now, but please don't hesitate to respond and re-open if you're still running into problems!

**Comment by egglessness** [comment]
Hi @StephenHinck,

Unfortunately I'm still unable to get query results before the transaction times out:

- I tried to add the environment variable to the bloodhound container, but I receive a timeout error (although the error message is slightly different this time):
```
{"level":"warn","time":"2023-08-18T10:18:09.8040069Z","message":"Writing API Error. Status: 504. Message: [{ request took longer than the configured timeout: 30 second(s)}]"}
```
It seems that the error is thrown by the API, and not by Neo4j.

- I also tried to inject the `Prefer` header and it would work, except that the query needs about 1 minute and a half to run and I cannot set a timeout greater than 60 seconds. If I set 61 seconds, for instance, the timeout comes back to 30 seconds.

**Comment by freeload101** [comment]
> * If I set 61 seconds, for instance, the timeout comes back to 30 seconds.

Any luck ? I'm getting this. even with environment:
      - bhe_disable_cypher_qc=true
```


bh-bloodhound-1  | {"level":"info","time":"2023-10-27T11:36:40.349243725Z","message":"Cypher query cost is: 9.00. Reduction factor for query is: 1. Available timeout for query is now set to: 30.00 seconds"}
bh-bloodhound-1  | {"level":"warn","time":"2023-10-27T11:37:10.395127051Z","message":"Writing API Error. Status: 500. Message: [{ driver error: Neo4jError: Neo.ClientError.Transaction.TransactionTimedOut (The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. The transaction has not completed within the specified timeout (dbms.transaction.timeout). You may want to retry with a longer timeout. ) - query: match p = shortestPath((n)-[:Owns|GenericAll|GenericWrite|WriteOwner|WriteDacl|MemberOf|ForceChangePassword|AllExtendedRights|AddMember|HasSession|Contains|GPLink|AllowedToDelegate|TrustedBy|AllowedToAct|AdminTo|CanPSRemote|CanRDP|ExecuteDCOM|HasSIDHistory|AddSelf|DCSync|ReadLAPSPassword|ReadGMSAPassword|DumpSMSAPassword|SQLAdmin|AddAllowedToAct|WriteSPN|AddKeyCredentialLink|SyncLAPSPassword|WriteAccountRestrictions*1..]->(g:Group)) where g.objectid ends with \"-512\" and n <> g return p}]"}
bh-bloodhound-1  | {"level":"warn","time":"2023-10-27T11:37:10.395157606Z","message":"Writing API Error. Context Deadline Exceeded while writing JSON response."}
```

**Comment by manwefm** [comment]
Hi,
I added the following parameter in docker-compose :
- NEO4J_dbms_transaction_timeout=3600
And the Prefer header :
Prefer: wait=600

But now I am getting this error :
{"level":"warn","time":"2023-12-15T14:20:30.171087071Z","message":"POST /api/v2/graphs/cypher took longer than the configured timeout of 70 seconds"}

Where can I increase this 70 seconds timeout please ? Thank you.
